In [36]:
# import math
# math.sqrt(12)
#math.sqrt(23)

import math as m
m.sqrt(12)     #all operations called on m.


#numpy is library in python that has c++ code. for faster.
#use numpy array as they r faster tahn list
#homogenous entries only.
import numpy as np
#to make array
a=np.zeros(10)   #array of size 10, each 0.  #by default in float
print(a)
a.dtype   #to check data type of

a[1]=3.4
print(a)
a[1]="3.4"  #convert string to float first
print(a)

i=a.mean()
print(i)
i=a.shape  #10-> 1d array of size 10.
b=np.zeros((10,5))  #for 2d array pass tuple
i=b.shape
print(i)
print(i)
b=np.zeros(10,dtype=int)
print(b)
b=np.array([1,2,3])  #to make using list
print(b)

a=np.array([1,2,3])
b=np.array([2,3,4])
a+b  #instead of concat it does vector addition of each element of a[i] , b[i].
a*2   #element wise multiply.

a=np.array([1,2,3,4.5]) #concat all to float to make homo
print(a)

#if in 2d arrays , it broadcasts.
a=np.zeros((3,4))   #2d arrays of 3*4
b=np.zeros((1,4))
a+b  #it broadcasts


#to find standard deviation
a=np.array([1,3,5])
a=a-a.mean()
a=a**2
a=a.mean()
print(a)

#multiply
a=np.array([[1,2,3],[3,4,5]]) #2d array with 2 rows:1,2,3 & 3,4,5
b=np.array([[1,2],[3,4],[7,5]])
print(a)
print(b)
#a*b  erros as it will broadcast
a=a.dot(b)  #does dot product i.e actual matrix multiplication of a*b
print(a)

a=np.array([1,2,3],dtype='int')
a.astype(float)  #to typecast all values.
a.astype(int)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.  3.4 0.  0.  0.  0.  0.  0.  0.  0. ]
[0.  3.4 0.  0.  0.  0.  0.  0.  0.  0. ]
0.33999999999999997
(10, 5)
(10, 5)
[0 0 0 0 0 0 0 0 0 0]
[1 2 3]
[1.  2.  3.  4.5]
2.6666666666666665
[[1 2 3]
 [3 4 5]]
[[1 2]
 [3 4]
 [7 5]]
[[28 25]
 [50 47]]


array([1, 2, 3])