In [23]:
#implementation of neural network
#forward propagation without hidden layer

#making neural network with no hidden layer
import numpy as np

In [24]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T   #and gate  #to keep y in 2d
Y

array([[0],
       [0],
       [0],
       [1]])

In [25]:
def sig(z):     #sigmoid fn
    return 1/(1+np.exp(-z))

In [26]:
def dsig(z):
    return sig(z)(1-sig(z))

In [27]:
weights=2*np.random.random((2,1))-1  #taking  2 weights using np.random. *2 and -1 to keep b/w -1 and 1

In [28]:
bias=np.random.random(1)*2-1

In [29]:
output0=X  #for i/p layer
output=sig(np.dot(output0,weights)+bias)
output

array([[0.72511098],
       [0.51062603],
       [0.83418294],
       [0.66554878]])

Forward propagation with hidden layer.

In [30]:
wh=2*np.random.random((2,2))-1   #weights in hidden layer
bh=np.random.random((1,2))*2-1    #bias in hidden layer
wo=2*np.random.random((2,1))-1  #weights in o/p layer
bo=np.random.random(1)*2-1 #bias in o/p

In [31]:
output0=X
outputH=sig(np.dot(output0,wh)+bh)
output=sig(np.dot(outputH,wo)+bo)
output

array([[0.44393866],
       [0.42168527],
       [0.45750493],
       [0.43555298]])