In [1]:
import numpy as np

In [11]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
Y

array([[0],
       [0],
       [0],
       [1]])

In [16]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [17]:
def dsig(z):
    return sig(z)(1 - sig(z))

In [8]:
weights = 2 * np.random.random((2,1)) - 1
bias = np.random.random(1)* 2 - 1

In [12]:
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[ 0.49507937],
       [ 0.31537735],
       [ 0.66528183],
       [ 0.48288346]])

In [13]:
wh = 2 * np.random.random((2,2)) - 1
bh = np.random.random((1, 2))* 2 - 1
wo = 2 * np.random.random((2,1)) - 1
bo = np.random.random(1)* 2 - 1

In [15]:
output0 = X
outputH = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputH, wo) + bo)
output

array([[ 0.45432884],
       [ 0.45905582],
       [ 0.46010726],
       [ 0.46388176]])